apiVersion: v1
kind: Service
metadata:
  name: rbsoft-app-service
spec:
  selector:
    app: rbsoft-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4200
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbsoft-app
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: rbsoft-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rbsoft-app
    spec:
      containers:
      - name: rbsoft-app 
        image: arnobdev/rbsoft-app:v-06
        imagePullPolicy: Always
        ports:
          - containerPort: 4200
            name: api-port
            protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rbsoft-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: rbsoft.32-1.xyz
    http:
      paths:
       - path: /
         pathType: Prefix
         backend:
            service:
               name: rbsoft-app-service
               port:
                  number: 80