name: Production BDayPay

on: 
  push:
    branches:
      -  main

jobs:
  Deploy:
    name: BDayPay Backend Deploy Process
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Get brandh tag
        id: vars
        shell: bash
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/heads/}-$(git rev-parse --short HEAD)"
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_PASSWORD }}

      - name: Build and push image to Docker Hub
        run: |
          docker build . -t arnobdev/rbsoft-app:${{ steps.vars.outputs.tag }}
          docker push arnobdev/rbsoft-app:${{ steps.vars.outputs.tag }}
          
      - name: Push the build image to the DO kubectl
        uses: arn-ob/do-kubectl-action@main
        with:
          do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
          do_cluster_certificate: ${{ secrets.DO_CLUSTER_CERTIFICATE }}
          do_deployment_name: rbsoft-app
          do_container_name: rbsoft-app
          do_image_tag: arnobdev/bdaypay:${{ steps.vars.outputs.tag }}
